/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#605d63',
        'primary-fixed': '#f7d8ff',
        'tertiary-fixed-dim': '#cdc3d5',
        'surface-tint': '#8440a5',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'on-secondary-fixed': '#1c1b20',
        primary: '#570d78',
        'brand-accent': '#F9F4FB',
        'light-tint': '#F9F4FB',
        divider: '#E8DDF0',
        'urgent-red': '#E74C3C',
        'success-green': '#2ECC71',
        'on-primary-fixed-variant': '#6a258b',
        outline: '#7f7381',
        'inverse-surface': '#303031',
        'on-error': '#ffffff',
        'surface-container': '#efeded',
        'on-tertiary-fixed-variant': '#4b4453',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#310048',
        'surface-container-high': '#e9e8e7',
        'surface-bright': '#fbf9f8',
        'on-tertiary-fixed': '#1f1926',
        'tertiary-fixed': '#eadef2',
        'on-secondary': '#ffffff',
        'outline-variant': '#d0c2d1',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#c9c5cc',
        'on-tertiary-container': '#c4bacc',
        'error-container': '#ffdad6',
        'inverse-primary': '#e9b3ff',
        'primary-fixed-dim': '#e9b3ff',
        'secondary-fixed': '#e5e1e8',
        'on-primary-container': '#e4a6ff',
        'secondary-container': '#e5e1e8',
        'on-surface-variant': '#4d4350',
        background: '#fbf9f8',
        'tertiary-container': '#514a59',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e2',
        'on-secondary-container': '#666369',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f2f0f0',
        tertiary: '#3a3342',
        surface: '#fbf9f8',
        'surface-dim': '#dbdad9',
        'primary-container': '#702c91',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#48464b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sidebar_width: '240px',
        container_max_width: '1200px',
        margin_desktop: '32px',
        gutter: '24px',
        margin_mobile: '16px',
        space_unit: '8px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat'],
        'body-md': ['Montserrat'],
        'headline-xl': ['Montserrat'],
        'label-lg': ['Montserrat'],
        'label-sm': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'body-lg': ['Montserrat'],
        'headline-sm': ['Montserrat'],
        'label-md': ['Montserrat'],
        'body-sm': ['Montserrat'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['16px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
