/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: 'var(--color-secondary)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        primary: 'var(--color-primary)',
        'brand-accent': 'var(--color-brand-accent)',
        'light-tint': 'var(--color-light-tint)',
        divider: 'var(--color-divider)',
        'urgent-red': 'var(--color-urgent-red)',
        'success-green': 'var(--color-success-green)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        outline: 'var(--color-outline)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'on-error': 'var(--color-on-error)',
        'surface-container': 'var(--color-surface-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-secondary': 'var(--color-on-secondary)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'error-container': 'var(--color-error-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        background: 'var(--color-background)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-background': 'var(--color-on-background)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        tertiary: 'var(--color-tertiary)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'primary-container': 'var(--color-primary-container)',
        error: 'var(--color-error)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sidebar_width: '240px',
        container_max_width: '1200px',
        margin_desktop: '32px',
        gutter: '24px',
        margin_mobile: '16px',
        space_unit: '8px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat'],
        'body-md': ['Montserrat'],
        'headline-xl': ['Montserrat'],
        'label-lg': ['Montserrat'],
        'label-sm': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'body-lg': ['Montserrat'],
        'headline-sm': ['Montserrat'],
        'label-md': ['Montserrat'],
        'body-sm': ['Montserrat'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['16px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      keyframes: {
        'toast-slide-in': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        }
      },
      animation: {
        'toast-slide-in': 'toast-slide-in 0.3s ease-out forwards',
      }
    },
  },
  plugins: [],
}
